# Generated by Django 5.2.13 on 2026-04-20 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я майстра або назва боксу")),
            ],
            options={
                'verbose_name': 'Майстер/Бокс',
                'verbose_name_plural': 'Майстри та Бокси',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва послуги')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Рік випуску')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN-код')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата запису')),
                ('time', models.TimeField(verbose_name='Час запису')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('in_progress', 'В роботі'), ('done', 'Готово'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.car', verbose_name='Автомобіль')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.master', verbose_name='Майстер')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
